//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting_equipment
    {
        public int ID { get; set; }
        public string Sports_food { get; set; }
        public string Cloth { get; set; }
        public string Shoes { get; set; }
        public string Sports_equipment { get; set; }
        public string hygiene_products { get; set; }
    }
}
