//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Secondname { get; set; }
        public System.DateTime DateBirth { get; set; }
        public string Adress { get; set; }
        public string Nameschool { get; set; }
        public string Nameparent { get; set; }
        public string Surnameparent { get; set; }
        public string Secondnameparent { get; set; }
        public string Placeofwork { get; set; }
        public string Phone { get; set; }
        public string Category { get; set; }
    }
}
