//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vieviw
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Full_years { get; set; }
        public System.DateTime Datevieviwing { get; set; }
        public string Phone { get; set; }
        public string Phonemaintainers { get; set; }
    }
}
